/*
=============================================================
Product Performance & Revenue Analytics
=============================================================
Purpose:
    This query builds a product-level analytics report by
    aggregating sales data and calculating key business metrics.

What this report answers:
1. How each product is performing in terms of sales and orders
2. How recently a product was sold (recency)
3. Average revenue per order
4. Average monthly revenue during the product’s active period
5. Product performance classification (High / Mid / Low)

Designed for:
- Data Analyst / BI Analyst portfolios
- Product performance analysis
- Interview and GitHub showcase
=============================================================
*/

-- Step 1: Base query
-- Collects essential product and transaction-level details
CREATE VIEW gold.report_products AS
WITH base_query AS (
    SELECT 
        p.product_name,
        p.category,
        p.subcategory,
        p.cost,
        p.start_date,
        f.order_number,
        f.customer_key,
        f.sales_amount,
        f.quantity,
        f.order_date
    FROM gold.fact_sales f
    LEFT JOIN gold.dim_products p
        ON f.product_key = p.product_key
    -- Exclude invalid transactions
    WHERE order_date IS NOT NULL
),

-- Step 2: Product-level aggregation
-- Summarizes sales data for each product
product_aggregation AS (
    SELECT
        product_name,
        category,
        subcategory,
        cost,
        -- Most recent sale date of the product
        MAX(order_date) AS last_order_date,
        -- Total number of orders for the product
        COUNT(order_number) AS total_orders,
        -- Total revenue generated by the product
        SUM(sales_amount) AS total_sales,
        -- Total quantity sold
        SUM(quantity) AS quntity_sold,
        -- Number of unique customers who purchased the product
        COUNT(DISTINCT customer_key) AS total_customers,
        -- Product active lifespan (in months)
        DATEDIFF(MONTH, MIN(start_date), MAX(order_date)) AS lifespan
    FROM base_query
    GROUP BY 
        product_name,
        category,
        subcategory,
        cost
)

-- Step 3: Final product analytics report
SELECT 
    product_name,
    category,
    subcategory,
    cost,
    total_orders,

    -- Product performance classification based on total sales
    CASE
        WHEN total_sales > 800000 THEN 'High Performer'
        WHEN total_sales BETWEEN 500000 AND 800000 THEN 'Mid Performer'
        ELSE 'Low Performer'
    END AS performance,

    total_sales,
    quntity_sold,
    total_customers,
    lifespan,

    -- Product recency: months since last sale
    DATEDIFF(MONTH, last_order_date, GETDATE()) AS recency,

    -- Average revenue generated per order
    CASE 
        WHEN total_orders = 0 THEN 0
        ELSE total_sales / total_orders 
    END AS avg_order_revenue,

    -- Average monthly revenue during the product’s active period
    CASE 
        WHEN lifespan = 0 THEN 0
        ELSE total_sales / lifespan 
    END AS avg_monthly_revenue

FROM product_aggregation;
